site_name: XenForo 2.0 Documentation
site_description: Developer Documentation for XenForo 2.0.
site_author: XenForo Ltd.

theme: readthedocs
theme_dir: xf2
extra_css: [extra.css]

pages:
- Getting started: index.md
- Add-on structure: add-on-structure.md
- Development tools: development-tools.md
- General concepts: general-concepts.md
- Routing basics: routing-basics.md
- Controller basics: controller-basics.md
- Entities, finders, and repositories: entities-finders-repositories.md
- Managing the schema: managing-the-schema.md
- Let's build an add-on: lets-build-an-add-on.md
- Designing styles: designing-styles.md
<<<<<<< Updated upstream
=======
# Appendix(es)
- 'Appendix: Scotch Box': scotchbox.md
- 'Appendix: Code Examples': code-examples.md
>>>>>>> Stashed changes

#repo_url: https://github.com/xenforo-ltd/xfdocs/
#edit_uri: edit/master/docs/

markdown_extensions:
  - admonition
  - toc:
      permalink: 

copyright: <a href="https://xenforo.com/" target="_blank">Development documentation for XenForo&trade; 2.0 &copy;2017 XenForo Ltd.</a>